{
  description = "Terminal clipboard utilities for Wayland";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    crane.url = "github:ipetkov/crane";

    fenix = {
      url = "github:nix-community/fenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      crane,
      fenix,
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems =
        fn:
        nixpkgs.lib.genAttrs systems (
          system:
          fn {
            inherit system;
            pkgs = nixpkgs.legacyPackages.${system};
          }
        );
    in
    {
      packages = forAllSystems (
        { system, pkgs }:
        let
          craneLib = (crane.mkLib pkgs).overrideToolchain fenix.packages.${system}.stable.toolchain;

          src = craneLib.cleanCargoSource ./.;

          commonArgs = {
            inherit src;
            strictDeps = true;
            cargoExtraArgs = "-p wl-clipboard-rs-tools --features dlopen";
          };

          cargoArtifacts = craneLib.buildDepsOnly commonArgs;
        in
        {
          default = craneLib.buildPackage (
            commonArgs
            // {
              inherit cargoArtifacts;

              nativeBuildInputs = with pkgs; [
                installShellFiles
                makeWrapper
              ];

              postInstall = ''
                # Install man pages generated by the build script
                for f in target/man/*.1; do
                  installManPage "$f"
                done

                # Install shell completions generated by the build script
                installShellCompletion --bash target/completions/*.bash
                installShellCompletion --fish target/completions/*.fish
                installShellCompletion --zsh target/completions/_*

                # Wrap binaries so dlopen can find libwayland-client.so at runtime
                for bin in $out/bin/*; do
                  wrapProgram "$bin" \
                    --prefix LD_LIBRARY_PATH : "${pkgs.lib.makeLibraryPath [ pkgs.wayland ]}"
                done
              '';
            }
          );
        }
      );

      devShells = forAllSystems (
        { system, pkgs }:
        {
          default = pkgs.mkShell {
            buildInputs = [
              (fenix.packages.${system}.stable.withComponents [
                "cargo"
                "clippy"
                "rustc"
                "rustfmt"
                "rust-src"
              ])
              pkgs.pkg-config
              pkgs.wayland
            ];
          };
        }
      );

      overlays.default = final: _prev: {
        wl-clipboard-rs-tools = self.packages.${final.system}.default;
      };
    };
}
